version: '3'
services:
  app:
    image: harbor.chay-techs.com/portfolio/portfolio-app:latest
    restart: always
    depends_on:
      - nginx
      
  nginx:
    image: harbor.chay-techs.com/portfolio/nginx:latest
    ports:
      - 8081:8080